[[Images]]
name="whaleAir"
type="tileSet"
frameWidth=16
file="whale/whaleAir.psd"

[[Images]]
name="whaleIdle"
type="tileSet"
frameWidth=16
file="whale/whaleIdle.psd"

[[Images]]
name="backgroundCity"
type="single"
file="city/backgroundCity.psd"

[[Images]]
name="building0"
type="tileSet"
frameWidth=8
parts=["wall", "window"]
file="building/building0TileSet.psd"

[[Music]]
name="city"
file="pd_city_0.mp3"

