# 
# ---Whale---
#
[[Images]]
name="whaleAir"
type="tileSet"
frameWidth=16
scaleMultiplier=10
file="whale/whaleAir.psd"

[[Images]]
name="whaleIdle"
type="tileSet"
frameWidth=16
scaleMultiplier=10
file="whale/whaleIdle.psd"

[[Images]]
name="whaleWalk"
type="tileSet"
frameWidth=16
scaleMultiplier=10
file="whale/whaleWalk.psd"

[[Images]]
name="whaleJump"
type="tileSet"
frameWidth=16
scaleMultiplier=10
file="whale/whaleJump.psd"

# 
# ---Enemies---
#

[[Images]]
name="biscuitEnemyIdle"
type="tileSet"
frameWidth=8
scaleMultiplier=10
file="enemies/biscuitEnemyIdle.psd"

[[Images]]
name="biscuitEnemyDeath"
type="tileSet"
frameWidth=8
scaleMultiplier=10
file="enemies/biscuitEnemyDeath.psd"

[[Images]]
name="biscutUFOIdle"
type="tileSet"
frameWidth=16
scaleMultiplier=10
file="enemies/biscutUFOIdle.psd"

[[Images]]
name="biscutUfoDeath"
type="tileSet"
frameWidth=16
scaleMultiplier=10
file="enemies/biscutUfoDeath.psd"

# 
# ---effects---
#

[[Images]]
name="speedLine"
type="single"
scaleMultiplier=4
file="effect/speedLine.psd"

# 
# ---tokens---
#

[[Images]]
name="tokenJumpUp"
type="single"
scaleMultiplier=2
file="token/jumpUp.psd"

[[Images]]
name="tokenSpeedUp"
type="single"
scaleMultiplier=2
file="token/speedUp.psd"

# 
# ---UI---
#

[[Images]]
name="uiLifeAmount"
type="tileSet"
scaleMultiplier=10
frameWidth=16
parts=["Amount1", "Amount2", "Amount3"]
file="ui/lifeAmount.psd"

[[Images]]
name="uiJumpAmount"
type="tileSet"
scaleMultiplier=10
frameWidth=16
parts=["Amount1", "Amount2", "Amount3", "Amount4"]
file="ui/jumpAmount.psd"

[[Images]]
name="uiSpeedAmount"
type="tileSet"
scaleMultiplier=10
frameWidth=16
parts=["Amount1", "Amount2", "Amount3", "Amount4", "Amount5"]
file="ui/speedAmount.psd"

# 
# ---Backgrounds---
#

[[Images]]
name="backgroundCity"
type="single"
scaleMultiplier=10
file="city/backgroundCity.psd"

[[Images]]
name="cityFog"
type="single"
scaleMultiplier=10
file="city/cityFog.psd"

[[Images]]
name="skyCity"
type="single"
scaleMultiplier=10
file="city/skyCity.psd"

# 
# ---Buildings---
#

[[Images]]
name="bulletSmallGreen"
type="single"
scaleMultiplier=10
file="bullet/bulletSmallGreen.psd"

[[Images]]
name="building0"
type="tileSet"
frameWidth=16
scaleMultiplier=5
parts=["wall", "window"]
file="building/building0TileSet.psd"

[[Images]]
name="building1"
type="tileSet"
frameWidth=8
scaleMultiplier=10
parts=["roofLeft", "roofMiddle", "roofRight", "botMiddle", "middleLeft", "middleRight"]
file="building/building1TileSet.psd"

[[Images]]
name="building2"
type="tileSet"
frameWidth=8
scaleMultiplier=10
parts=["window", "roofHanging", "roofClean", "middleWhite", "middleWhiteClean", "leftMiddle", "rightMiddle", "leftRoof", "rightRoof", "middleBlue"]
file="building/building2TileSet.psd"

[[Images]]
name="building3"
type="tileSet"
frameWidth=8
scaleMultiplier=10
parts=["leftMiddle", "roofTop", "roofLeft", "roofMiddle", "roofRight", "rightMiddle", "whiteMiddle", "windowMiddle"]
file="building/building3TileSet.psd"

[[Images]]
name="building4"
type="tileSet"
frameWidth=8
scaleMultiplier=10
parts=["leftMiddle", "rightMiddle", "middlePlain", "middleWindow", "signYellowTop", "signYellowBot", "signOrangeTop", "signOrangeBot", "signGreenTop", "signGreenBot", "signBlue", "signRed", "roofLeft", "roofMiddle", "roofRight"]
file="building/building4TileSet.psd"

[[Images]]
name="building5"
type="tileSet"
frameWidth=8
scaleMultiplier=10
parts=["roofLeft", "roofRight", "roofMiddle", "middleLeft", "middleRight", "middleWindow"]
file="building/building5TileSet.psd"


[[Sounds]]
name="byJumpTwo"
file="byJumpTwo.wav"

[[Sounds]]
name="whaleDamage"
file="whaleDamage.wav"

[[Sounds]]
name="biscuitDeath"
file="pdBiscuitDeath.wav"

[[Sounds]]
name="ufoBiscuitEnemyDeath"
file="ufoBiscuitEnemyDeath.wav"

[[Sounds]]
name="byLaserFour"
file="byLaserFour.wav"

[[Sounds]]
name="byCollect5"
file="byCollect5.wav"

[[Sounds]]
name="JdwBlowOne"
file="JdwBlowOne.wav"

[[Music]]
name="city"
file="pdCity0.mp3"

# ---------------------------------- #

# 
# --- karaoke ---
#

[[Images]]
name="karaokeBackground"
type="single"
scaleMultiplier=1
file="karaoke/karaokeBackground.psd"

[[Images]]
name="whaleSinging"
type="single"
scaleMultiplier=4
file="karaoke/whaleSinging.psd"

[[Sounds]]
name="bit8CoinOne"
file="bit8CoinOne.wav"

[[Sounds]]
name="bit8CoinOneRepeated"
file="bit8CoinOneRepeated.wav"

[[Music]]
name="karaokeRock"
file="pdRockBackground.mp3"

[[Karaoke]]
file="pdRock01/pdRock01.json"

# ---------------------------------- #

# 
# ---title screen---
#

[[Images]]
name="titleSceneArrow"
type="single"
scaleMultiplier=1
file="titleScene/titleSceneArrow.psd"

[[Images]]
name="titleSceneGameText"
type="single"
scaleMultiplier=1
file="titleScene/titleSceneGameText.psd"

[[Images]]
name="titleSceneText"
type="single"
scaleMultiplier=1
file="titleScene/titleText.psd"

[[Images]]
name="titleSceneBeach"
type="single"
scaleMultiplier=10
file="titleScene/titleSceneBeach.psd"

[[Images]]
name="titleSceneBeachWater"
type="tileSet"
scaleMultiplier=10
frameWidth=256
file="titleScene/titleSceneBeachWater.psd"

[[Music]]
name="city"
file="pdTitleScreen.mp3"

# ---------------------------------- #

#
# --- input icons ---
#

[[Icons]]
name="keyboardDark"
path="keyboard"
type="keyboard"
expression="^(?P<name>.*?)_Key_Dark\\.png$"

[[Icons]]
name="xboxSeries"
path="XboxSeriesX"
type="gamepad"
[Icons.Buttons]
a="XboxSeriesX_A.png"
b="XboxSeriesX_B.png"
x="XboxSeriesX_X.png"
y="XboxSeriesX_Y.png"
lb="XboxSeriesX_LB.png"
rb="XboxSeriesX_RB.png"
select="XboxSeriesX_View.png"
start="XboxSeriesX_Menu.png"
left_stick="XboxSeriesX_Left_Stick.png"
right_stick="XboxSeriesX_Right_Stick.png"