# 
# ---Whale---
#
[[Images]]
name="whaleAir"
type="tileSet"
frameWidth=16
scaleMultiplier=10
file="whale/whaleAir.psd"

[[Images]]
name="whaleIdle"
type="tileSet"
frameWidth=16
scaleMultiplier=10
file="whale/whaleIdle.psd"

[[Images]]
name="whaleWalk"
type="tileSet"
frameWidth=16
scaleMultiplier=10
file="whale/whaleWalk.psd"

[[Images]]
name="whaleJump"
type="tileSet"
frameWidth=16
scaleMultiplier=10
file="whale/whaleJump.psd"

# 
# ---Enemies---
#
[[Images]]
name="biscuitEnemyIdle"
type="tileSet"
frameWidth=8
scaleMultiplier=10
file="Enemies/biscuitEnemyIdle.psd"

# 
# ---Buildings---
#

[[Images]]
name="bulletSmallGreen"
type="single"
scaleMultiplier=10
file="bullet/bulletSmallGreen.psd"

[[Images]]
name="backgroundCity"
type="single"
scaleMultiplier=10
file="city/backgroundCity.psd"

[[Images]]
name="building0"
type="tileSet"
frameWidth=8
scaleMultiplier=10
parts=["wall", "window"]
file="building/building0TileSet.psd"

[[Sounds]]
name="byJumpTwo"
file="byJumpTwo.wav"

[[Music]]
name="city"
file="pd_city_0.mp3"

