[[Images]]
name="whaleAir"
frameWidth=16
file="whale/whaleAir.psd"

[[Images]]
name="whaleIdle"
file="whale/whaleIdle.psd"

[[Images]]
name="backgroundCity"
file="city/backgroundCity.psd"

[[Music]]
name="city"
file="pd_city_0.mp3"

