name: dev build
on:
  push:
    branches:
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
      - '!master'   # excludes master

jobs:
  build:
    name: dev build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests and make sure builds
        run: docker run -v ${PWD}:/app --entrypoint="bash" golang:1.16 /app/build.sh
      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash)
