name: dev build
on:
  push:
    branches:
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
      - '!master'   # excludes master

jobs:
  build:
    name: dev build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests
        uses: cedrickring/golang-action@1.6.0
        env:
          PROJECT_PATH: "."
      - name: Build conatiner
        run: docker build -f web/Dockerfile . -t wgmhd-web:latest
      - name: Build wasm version
        run: docker run wgmhd-web:latest
